# Generated by Django 4.0.4 on 2022-04-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('wear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_wear', to='wear.wear')),
            ],
        ),
    ]
